export const WALL_CREATE_REQUEST = 'WALL_CREATE_REQUEST'
export const WALL_CREATE_SUCCESS = 'WALL_CREATE_SUCCESS'
export const WALL_CREATE_FAIL = 'WALL_CREATE_FAIL'

export const WALL_GET_REQUEST = 'WALL_GET_REQUEST'
export const WALL_GET_SUCCESS = 'WALL_GET_SUCCESS'
export const WALL_GET_FAIL = 'WALL_GET_FAIL'

export const WALL_ADD_PRAYER_REQUEST = 'WALL_ADD_PRAYER_REQUEST'
export const WALL_ADD_PRAYER_SUCCESS = 'WALL_ADD_PRAYER_SUCCESS'
export const WALL_ADD_PRAYER_FAIL = 'WALL_ADD_PRAYER_FAIL'

export const WALL_ADD_ID_TO_LIST = 'WALL_ADD_ID_TO_LIST'

export const WALL_ADD_USERS_NAME = 'WALL_ADD_USERS_NAME'

export const WALL_ADD_REPLY_REQUEST = 'WALL_ADD_REPLY_REQUEST'
export const WALL_ADD_REPLY_SUCCESS = 'WALL_ADD_REPLY_SUCCESS'
export const WALL_ADD_REPLY_FAIL = 'WALL_ADD_REPLY_FAIL'
